### ISSUE TITLE
Do not attempt to deploy library to PyPI on each Travis CI environment

### ISSUE THREAD

**Issue by playpauseandstop** [playpauseandstop/Flask-And-Redis#21]
[Build #68](https://travis-ci.org/playpauseandstop/Flask-And-Redis/builds/495046231) at Travis CI failed cause Travis attempted to deploy (upload) new version of `Flask-And-Redis` library to PyPI from each Python version, which is wrong.

Need to fix `.travis.yml` config to allow deploy library only for python `3.7`.

**Comment by docapotamus** [comment]
Hi.

I was just looking for the docs link and saw this. I quickly checked the [docs](https://docs.travis-ci.com/user/deployment/#examples-of-conditional-deployment). I think the solution may be:

```
deploy:
  provider: pypi
  user: playpauseandstop
  password:
    secure: adlnY9sKpfJPdcpnh0SuhQ4iIbZozQ4uNMJ/UgAra4ft4FfiDhYKqqbz58mX0PSKhLcaA0RAeLeesMqqiKrEBRmmQeu7k/pM5kw3Z57B7H/zMIoHDqgbdUMvM3Jf6PZrgx5qat48ECGZHz0ImvQzwfr98i1k+wmJM5on2X6pWgU=
  distributions: sdist bdist_wheel
  on:
    branch: "master"
    python: "3.7"
    tags: true
```

I thought this may have been hard to test in a PR.
